<Type Name="DtsNoLogProviderAssignedException" FullName="Microsoft.SqlServer.Dts.Runtime.DtsNoLogProviderAssignedException">
  <TypeSignature Language="C#" Value="public sealed class DtsNoLogProviderAssignedException : Microsoft.SqlServer.Dts.Runtime.DtsException" />
  <TypeSignature Language="ILAsm" Value=".class public auto ansi serializable sealed beforefieldinit DtsNoLogProviderAssignedException extends Microsoft.SqlServer.Dts.Runtime.DtsException" />
  <TypeSignature Language="DocId" Value="T:Microsoft.SqlServer.Dts.Runtime.DtsNoLogProviderAssignedException" />
  <AssemblyInfo>
    <AssemblyName>Microsoft.SqlServer.ManagedDTS</AssemblyName>
    <AssemblyVersion>14.0.0.0</AssemblyVersion>
  </AssemblyInfo>
  <Base>
    <BaseTypeName>Microsoft.SqlServer.Dts.Runtime.DtsException</BaseTypeName>
  </Base>
  <Interfaces />
  <Docs>
    <summary>Die Ausnahme, die ausgelöst wird, um anzugeben, dass ein interner Fehler aufgetreten, wenn ein verwalteter Wrapper für ein systemeigenes Objekt verwendet wird, die nicht vom Typ ist <see cref="T:Microsoft.SqlServer.Dts.Runtime.LogProvider" />.</summary>
    <remarks>To be added.</remarks>
  </Docs>
  <Members />
</Type>
